<script setup>
import { t } from '../../i18n'
defineOptions({ name: 'AppFooter' })
</script>
<template>
  <footer class="mt-16 bg-slate-950 text-slate-300">
    <div class="mx-auto max-w-7xl px-4 py-12 sm:py-14"><div class="grid gap-10 sm:grid-cols-2 lg:grid-cols-4"><div><RouterLink to="/" class="inline-flex items-center gap-3"><img src="/IMG/image.png" alt="Smart Khmer" class="h-11 w-11 rounded-xl" /><span class="font-bold text-white">Smart Khmer</span></RouterLink><p class="mt-4 max-w-xs text-sm leading-6 text-slate-400">{{ t('footerDescription') }}</p><div class="mt-5 flex gap-2"><a href="#" class="social-link" aria-label="Facebook"><i class="fa-brands fa-facebook-f"></i></a><a href="#" class="social-link" aria-label="Instagram"><i class="fa-brands fa-instagram"></i></a><a href="#" class="social-link" aria-label="Telegram"><i class="fa-brands fa-telegram"></i></a></div></div><div><h3 class="footer-title">{{ t('footerShop') }}</h3><nav class="footer-links"><RouterLink to="/products">{{ t('footerAllProducts') }}</RouterLink><RouterLink to="/categories">{{ t('navCategories') }}</RouterLink><RouterLink to="/wishlist">{{ t('footerWishlist') }}</RouterLink><RouterLink to="/cart">{{ t('footerCart') }}</RouterLink></nav></div><div><h3 class="footer-title">{{ t('footerCare') }}</h3><nav class="footer-links"><a href="#">{{ t('footerHelp') }}</a><a href="#">{{ t('footerShipping') }}</a><a href="#">{{ t('footerReturns') }}</a><a href="#">{{ t('footerContact') }}</a></nav></div><div><h3 class="footer-title">{{ t('footerContact') }}</h3><div class="space-y-3 text-sm text-slate-400"><p><i class="fa-solid fa-location-dot mr-2 text-emerald-400"></i>{{ t('footerLocation') }}</p><p><i class="fa-solid fa-phone mr-2 text-emerald-400"></i>+855 12 345 678</p><p><i class="fa-solid fa-envelope mr-2 text-emerald-400"></i>support@smartkhmer.com</p></div></div></div><div class="mt-12 flex flex-col gap-2 border-t border-slate-800 pt-6 text-center text-xs text-slate-500 sm:flex-row sm:justify-between"><span>© 2026 Smart Khmer Marketplace</span><span>{{ t('footerSecure') }}</span></div></div>
  </footer>
</template>
